InsightSoftwareConsortium/itkwidgets

examples/2DImage.ipynb
examples/3DImage.ipynb

ENH: Assume itkwidgets is installed in the examples

---

itkwidgets/trait_types.py
tests/test_trait_types.py

BUG: Fix base 64 encoding type with Python 3

---

examples/ImageJImgLib2.ipynb
itkwidgets/widget_viewer.py

Example from:
https://github.com/CellProfiler/notebooks/blob/95a2558060075b0c8c9ad254413fac8dacfc2d12/imagej_pyjnius_demo.ipynb
Co-authored-by: Curtis Rueden <ctrueden@wisc.edu>

ENH: ImageJ ImgLib2 example

---

examples/ImageJImgLib2.ipynb

DOC: Simplify ImageJ initialization

---

README.rst
binder/environment.yml
binder/postBuild

adding binder support with iopub limit set correctly: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/issues/27

adding binder support

---

README.rst

Requires Jupyter Notebook version 5.3 and above

DOC: We do not need to explicitly install / enable

---

examples/2DImage.ipynb
examples/3DImage.ipynb
examples/ImageJImgLib2.ipynb
examples/vtkImageData.ipynb
js/package.json

Addresses #42. A new button is added to choose between linear and nearest neighbor interpolation of the slices.

Interpolation

---

.gitignore
README.rst
examples/scikit-image.ipynb

@stefanv here's what we did at ImageXD.

ENH: Add scikit-image example

---

.gitignore
examples/RecordAVideo.ipynb
itkwidgets/widget_viewer.py
js/lib/viewer.js
js/package.json
setup.py

@maartenbreddels bringing the awesome capabilities of `ipywebrtc`! :battery:

ENH: Add support for creating a video recording

---

setup.py

Improved NumPy bridge support.

BUG: Add itk-core>=4.13.1 dependency

---

README.rst
js/package.json

ENH: Add and document keyboard shortcuts

---

js/lib/viewer.js

Firefox requires .getContext to be called on a canvas before
.captureStream.
Closes #90

BUG: Fix stream initialization on Firefox

---

itkwidgets/widget_viewer.py

ExtractImageFilter effectively moves the Origin.

BUG: Set Origin when downsampling

---

README.rst
examples/vtki.UniformGrid.ipynb

@akaszynski please take a look.

DOC: Add vtki.UniformGrid example

---

js/package.json

BUG: Bump itk-vtk-viewer to 6.6.1

---

itkwidgets/trait_types.py
itkwidgets/widget_viewer.py
js/lib/viewer.js
js/package-lock.json
js/package.json

This results in significant improvements in volume rendering quality and
speed when exploring large images.
This simplifies rendering updates.
Coupled with a fix to the re-use of memory with itk.ExtractImageFilter,
this addresses Python kernel crashes, Issue #120.

ENH: Bump vtk.js and itk-vtk-viewer

---

itkwidgets/trait_types.py

Documentation follow-up to #149

DOC: VTKPolyData traitlet documentation improvements

---

itkwidgets/_transform_types.py
tests/test_transform_types.py

Closes https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/issues/156

BUG: Handle arrays with non-continuous memory, eg: slicing numpy arrays

---

js/package-lock.json
js/package.json
setup.py

JupyterLab 1.0 requires an update the the @jupyter-widgets/base package:
https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/changelog.md#updates-for-widget-maintainers
Closes #155

BUG: Support builds with JupyterLab 1.0

---

examples/pyvista.PolyDataAndImageData.ipynb
js/lib/viewer.js
js/package-lock.json
js/package.json

@banesullivan this addresses mixed volumes / meshes.
Closes #164

Geometry and images

---

itkwidgets/widget_viewer.py
js/lib/viewer.js
js/package-lock.json
js/package.json

ENH: Support setting point set and geometry opacities

---

README.rst
examples/ImageWithAnisotropicPixelSpacing.ipynb

@GenevieveBuckley please take a look.

DOC: Add example for image with anisotropic spacing

---

itkwidgets/_transform_types.py
itkwidgets/trait_types.py
js/lib/viewer.js
tests/test_transform_types.py

Geometry point data

---

js/package-lock.json
js/package.json

Suggested-by: Bane Sullivan <banesullivan@gmail.com>
@banesullivan

ENH: Change the default geometry colormap from Plasma to Viridis

---

README.rst
examples/pyvista.PolyData.ipynb
examples/pyvista.StructuredGrid.ipynb
examples/pyvista.UnstructuredGrid.ipynb
itkwidgets/_transform_types.py

@banesullivan please take a look.
@jourdain any thoughts or tips here?

Pyvista unstructured grid example

---

itkwidgets/_transform_types.py

Follow up to https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/pull/178#issuecomment-515812912

Add geometry support for vtkImageData

---

examples/SpecifyAColormap.ipynb
itkwidgets/trait_types.py

This is more appropriate for a lookup table.

BUG: Remove ListedColormap from cmap support

---

examples/Mayavi.ipynb
itkwidgets/widget_viewer.py

ENH: Add a Mayavi example

---

js/lib/viewer.js

@fjug getting this issue we observed addressed :ok_hand:

BUG: Update the camera parameters on end mouse wheel

---

js/package-lock.json
js/package.json

Also bringing in many other improvements.

ENH: Add scale bar

---

js/package-lock.json
js/package.json

Re-applies a non-default colormap when the image is updated.

BUG: Fix custom color map with ROI selection

---

examples/3DImage.ipynb

DOC: Use urllib.request in 3DImage example

---

itkwidgets/widget_viewer.py
js/lib/viewer.js
js/package-lock.json
js/package.json

Closes #200
The itk-vtk-viewer bump also Closes #238

ENH: Add traitlet for volume rendering blend mode

---

.gitignore
README.rst
examples/SegmentationSkeleton.ipynb
itkwidgets/_transform_types.py
js/lib/viewer.js

@jni loved re-discovering skan to help with skeleton visualization! :heart: 
@phcerdan I wonder if SGEXT could be available in a Python package so we could also use it to perform the skeletonization?
Outputs:

Skeleton visualization with skan.csr.Skeleton support

---

requirements.txt
setup.py

For JupyterLab builds re: https://github.com/matplotlib/jupyter-matplotlib/issues/163

BUG: Require ipympl>=0.4.1

---

js/package-lock.json
js/package.json

BUG: Initialize all geometry opacities in JavaScript

---

README.rst

@romangrothausmann does this work on your setup?

DOC: Describe how to disable scrolling in JupyterLab

---

js/lib/viewer.js

Causes zoom sync in the compare widget.

BUG: Apply camera updates with 2D images

---

examples/pyvista.PolyData.ipynb
itkwidgets/trait_types.py
js/package-lock.json
js/package.json

Closes #175 
@banesullivan @akaszynski please take a look.

ENH: Enable specification of geometry and point set names

---

.gitignore
README.rst
examples/PointBasedSpatialObject.ipynb
itkwidgets/_transform_types.py
js/lib/viewer.js

Based on:
https://github.com/KitwareMedical/ITKTubeTK/blob/7dbad677ed989cc7ec91748158c064088dc315f8/examples/ITKSpatialObjects-SimpleExample.ipynb
@aylward please take a look!
Testing with ITK 5.0.1, a few spatial issues:
Maybe this is addressed in 5.1.0?
With ITK 5.1.0, we could accelerate with the `CastSpatialObjectFilter` :sunglasses: .

ENH: Add support for itk.PointBasedSpatialObject's

---

js/package-lock.json
js/package.json

Reduces cropping widget handle size.

BUG: Update itk-vtk-viewer to 9.12.3

---

js/package-lock.json
js/package.json

@martinRenou following your lead -- looks good?

ENH: Add support for JupyterLab 2

---

examples/PointBasedSpatialObject.ipynb

Requires itk-5.1rc3 or later.
Closes #281 
@aylward awesome work!

DOC: Display vessels overlaid on image in PointBasedSpatialObject

---

setup.py

BUG: Add ZstdDecompressWasm.wasm to setup.py data files

---

.github/workflows/build-test.yml

ENH: Add CI testing for Python 3.8

---

examples/Mesh.ipynb

DOC: Mesh examples uses itk.meshread

---

js/package-lock.json
js/package.json

BUG: Better WASM location support for JupyterLab.

---

js/lib/viewer.js
js/package-lock.json
js/package.json

Addressed by web worker pool improvements in itk.js.
Closes #307

BUG: Fix multi-object data loading

---

setup.py

BUG: Update dependencies for to 5.1.0.post1

---

examples/InteractiveParameterExploration.ipynb

DOC: Use continuous_update=False in example

---

js/package-lock.json
js/package.json

Address decompression with many small polydata's.

BUG: Bump itk.js to 13.1.1

---

examples/LabelMap.ipynb
examples/VolumeOpacityTransferFunction.ipynb
itkwidgets/widget_viewer.py
js/lib/viewer.js
js/package-lock.json
js/package.json

Channels blend background

---

js/package-lock.json
js/package.json

See: https://github.com/Kitware/itk-vtk-viewer/issues/296

BUG: Keep volume rendering quality when switching tabs

---

README.rst
examples/LabelImages.ipynb
itkwidgets/widget_viewer.py
js/lib/viewer.js

More consistent with ITK naming conventions.

STYLE: Rename label_map to label_image

---

.github/workflows/notebook-test.yml
treebeard.yaml

ENH: Also test 2DImage.ipynb notebook in CI

---

README.rst

Move back to JupyterLab after we have JupyterLab 3 support

DOC: Use Jupyter Notebook binder paths

---

itkwidgets/widget_viewer.py

1. Improve handling Mayavi objects to be far more robust.
2. Fix an issue with using lists as default arguments. This would cause
problems when view is called multiple times resulting in the last
call rendering all the previous actors as well.

BUG: Fix a few issues with the view function.

---

.github/workflows/build-test.yml
requirements.txt

@tbirdso thanks for the earlier patch, we have to backtrack here a bit, but we can revert after 5.3.0 is out.

Version deps

---

.github/workflows/publish.yml
utilities/release-notes.py

REL: Add workflow for publishing PyPI package

---

itkwidgets/integrations/__init__.py
itkwidgets/viewer.py

Add support for labels
Relies on Kitware/itk-vtk-viewer#522

Image label

---

.github/workflows/publish.yml
pyproject.toml

REL: Move from flit to hatch

---

docs/development.md

The requirements-dev.txt file has been removed, so mention of it should be removed from documentation.

DOC: Remove mention of requirements-dev.txt

---

itkwidgets/_initialization_params.py
itkwidgets/integrations/__init__.py
itkwidgets/viewer.py

When the choose-ui branch (b0a7aa3) was merged in after the label_images (a54c462) branch it seems that some conflicts were automatically but incorrectly resolved. This PR cleans up those conflicts to support both features.

BUG: Incorrectly resolved conflicts created series of bugs

---

.github/workflows/publish.yml
pyproject.toml

REL: Do not include examples or node_modules in release

---

itkwidgets/viewer.py

Closes https://github.com/InsightSoftwareConsortium/itkwidgets/issues/503

BUG: Fix MUI URL

---

itkwidgets/viewer.py

File naming has been updated in itk-viewer-bootstrap-ui version 0.7.4

Update boostrap ui URL

---

itkwidgets/__init__.py

This should now be infered from the tagged release on GitHub

REL: Remove explicit version tag

---

itkwidgets/viewer.py

The list was defined but was not being used to properly queue requests.
Fixes #524

BUG: Use deferred methods list

---

itkwidgets/trait_types.py

Throws an error with Python 3.10.
Closes #511

BUG: import Sequence from collections.abc

---

.github/workflows/notebook-test.yml
itkwidgets/integrations/__init__.py
itkwidgets/integrations/itk.py
itkwidgets/integrations/vtk.py
itkwidgets/integrations/xarray.py
pyproject.toml

ENH: Python 3.7 support

---

examples/Hello3DWorld.ipynb
examples/NumPyArrayPointSet.ipynb
examples/integrations/MONAI/transform_visualization.ipynb
examples/integrations/PyVista/LiDAR.ipynb
examples/integrations/PyVista/UniformGrid.ipynb
examples/integrations/dask/DaskArray.ipynb
examples/integrations/itk/3DImage.ipynb
examples/integrations/vtk/vtkImageData.ipynb
examples/integrations/vtk/vtkPolyDataPointSet.ipynb
examples/integrations/xarray/DataArray.ipynb
examples/integrations/zarr/OME-NGFF-Brainstem-MRI.ipynb
itkwidgets/viewer.py

When running a notebook in Colab the viewer was failing on `to_ngff_zarr`. It seems that in Colab specifically there are issues using Dask from an asynchronous function. By moving this to the (now) synchronous setup function we avoid this issue.
This branch also adds Colab badges to the notebooks.

Colab set image

---

itkwidgets/viewer_config.py

Fixes for transfer function editor
closes #565

feat(viewer): no interpolation on labels, categorical color maps

---

MANIFEST.in

BUG: Add requirements.txt to MANIFEST.in

---

.github/workflows/notebook-test.yml
.github/workflows/publish.yml
itkwidgets/integrations/environment.py

Avoid recent environment dependency check failures.

BUG: Install all package dependencies in CI

---

pyproject.toml

BUG: Avoid dask.array chunk size 0

---

itkwidgets/viewer_config.py

Brings in: https://github.com/Kitware/itk-vtk-viewer/pull/633
Closes #596

BUG: Update viewer for image orientation fix

---

itkwidgets/viewer_config.py

Incorporates https://github.com/Kitware/itk-vtk-viewer/pull/632

ENH: Add label image resampling support

---

.github/workflows/build-test.yml
requirements.txt

BUG: Constrain ipydatawidgets to <4.3.3

---

docs/jupyterlite/jupyterlite_config.json
pyproject.toml

BUG: Bump ngff-zarr to 0.2.0

---

itkwidgets/viewer_config.py

This limits the step value for the window/level interactor to 10 (values >= 100 reduce reactivity to near nothing).

BLD: Bump itk-vtk-viewer 14.35.0 -> 14.35.1

---

itkwidgets/viewer.py

Keyword args were being lost. Make sure they're not.

FIX: Do not ignore keyword args passed to viewer

---

.readthedocs.yml

COMP: Add .readthedocs.yml

---

itkwidgets/viewer_config.py

Adds a fix that improves the windowing step.

Bump itk-vtk-viewer to 14.39.0

---

itkwidgets/integrations/__init__.py
pyproject.toml

ENH: Add support for itkVectorImage

---

itkwidgets/viewer_config.py

Incorporates fixes for negative direction cosines and different number of scales in fixed and moving images.

FIX: bump itk-vtk-viewer to 14.41.3

---

itkwidgets/viewer_config.py

Allows user to display a bounding box around each of the image layers.
fixes #661
fixes #666

ENH: Add bounding box feature

---

pyproject.toml

Closes #655 via https://github.com/thewtex/ngff-zarr/pull/35

BUG: Bump ngff-zarr dep to >= 0.4.3

---

.github/workflows/notebook-test.yml
pyproject.toml

Causing the CI test failures in #589

MAINT: Drop support for Python 3.7; EOL was 6/27/23

---

pyproject.toml

Resolved via https://github.com/imjoy-team/imjoy-elfinder/pull/607

aiohttp version workaround update

---

itkwidgets/viewer_config.py

* Add intensity data value tooltip to control points
* Move color range control points lower
* Add middle color range control point

ENH: update transfer function editor color range features

---

itkwidgets/_type_aliases.py
itkwidgets/viewer.py

Add docstrings to the `ViewerRPC` and `Viewer` classes

Docstrings

---

itkwidgets/cell_watcher.py

Once we've processed all pending cells, reset the abort flag

---

README.md
docs/deployments.md
docs/jupyterlite/files/Hello3DWorld.ipynb
docs/quick_start_guide.md
environment.yml
examples/EnvironmentCheck.ipynb
examples/GettersAndSetters.ipynb
examples/Hello3DWorld.ipynb
examples/NumPyArrayPointSet.ipynb
examples/integrations/MONAI/transform_visualization.ipynb
examples/integrations/PyImageJ/ImageJImgLib2.ipynb
examples/integrations/PyVista/LiDAR.ipynb
examples/integrations/PyVista/UniformGrid.ipynb
examples/integrations/dask/DaskArray.ipynb
examples/integrations/itk/3DImage.ipynb
examples/integrations/itk/DICOM.ipynb
examples/integrations/itk/IDC_Seg_Primer_Examples.ipynb
examples/integrations/itk/MulticomponentNumPy.ipynb
examples/integrations/itk/SelectROI.ipynb
examples/integrations/itk/ThinPlateSpline.ipynb
examples/integrations/itkwasm/3DImage.ipynb
examples/integrations/itkwasm/SelectROI.ipynb
examples/integrations/vtk/vtkImageData.ipynb
examples/integrations/vtk/vtkPolyDataPointSet.ipynb
examples/integrations/xarray/DataArray.ipynb
examples/integrations/zarr/OME-NGFF-Brainstem-MRI.ipynb

In the docs and example notebooks the version referenced was pretty far behind the latest release. Bump the version to the latest 1.049.

Bump version in docs

---

itkwidgets/integrations/environment.py

Also remove duplicate try: except.
Suggested-by: @KumoLiu

BUG: imjoy_jupyterlab_extension argument to import_module

---

pyproject.toml

- ENH: Bump itkwasm dep version to 1.0b178
- BUG: Bump ngff-zarr dep to 0.8.7

ngff zarr bump
