- README.rst
- examples/2DImage.ipynb
- js/lib/itkConfigCDN.js
- js/lib/viewer.js
- js/package.json
- js/webpack.config.js
- setup.py
Pre-build the labextension with webpack so we can use the webpack rules
required for vtk.js and the custom webpack configuration for itk.js.
This is achieved by whitelisting the modules from being excluded by the
webpack-node-externals package.
Use the Unpkg CDN to provide the WebAssembly and WebWorker files loaded
dynamically.
Thanks to @saulshanabrook and @vidartf for the suggestions on how to address this issue.
Addresses #11
> BUG: Fix JupyterLab build configuration

- itkwidgets/widget_viewer.py
- js/lib/viewer.js
- js/package.json
- setup.py
@vidarf I am trying to use `ipydatawidgets` for a 2D float array that specifies a region of interest.
However, the change in the JavaScript model does not appear to be propagated to the Python kernel side. This is evident by the `viewer.roi_region()` still being all zeros in [this example notebook](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/master/examples/SelectRegionOfInterest.ipynb).
An ideas on what needs to change?
> ENH: Use ipydatawidgets for roi traitlet

- js/lib/viewer.js
When `.setImage` is called on the view proxy, the edge gradient value is
not used in the updated rendering.
Work around this by slightly tweaking the edge gradient value, which
causes it to be used.
This probably needs to be addressed somewhere in vtk.js at some point.
> BUG: Work around gradient opacity persistence

- setup.py
Without this, the Conda build fails because the .js/ folder is missing.
> BUG: Correct sdist paths

- setup.py
itk-core does not provide BinShrinkImageFilter which is required for downsampling.
> Fix #118: Add itk-filtering as a requirement.

- itkwidgets/widget_viewer.py
When performing interactive parameter exploration, the input image can
change.
@phcerdan this hopefully addresses the issue reported!
> BUG: Always set the downsampling filter input image

- README.rst
- examples/pyvista.PolyData.ipynb
@banesullivan I'm interested in your thoughts on how we can make this mesh rendering synergistic with pyvista.
> DOC: Add pyvista.PolyData example

- itkwidgets/_transform_types.py
Inspired by https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/pull/177#issuecomment-515263169
This makes it so users can pass most VTK mesh types:
- `vtkPolyData` / `pyvista.PolyData`
- `vtkUnstructuredGrid` / `pyvista.UnstructuredGrid`
- `vtkStructuredGrid` / `pyvista.StructuredGrid`
- `vtkRectilinearGrid` / `pyvista.RectilinearGrid` - can't this be volume rendered by VTKjs? maybe this should be handled differently?
and have those meshes' geometries extracted and viewed by `itkwidgets` without issue or confusion.
Lingering question - should we add `vtkImageData` here as well incase a user wants to treat the image data like geometry and not a volume (i.e. just plot the bounding surface)?
cc @thewtex
> Extract geometry for most non-PolyData VTK types

- README.rst
- examples/vtkplotter.ipynb
- itkwidgets/widget_viewer.py
This PR (partially) addresses #193 
- allows user to pass a list of vtkActor vtkVolume or vtkAssembly to the `view()` method using keyword `view(actors=[...])`.
- vtkplotter objects are automatically included as they inherit from the above classes
- added a usage example in `examples/vtkplotter.ipynb`
> vtkplotter integration

- README.rst
Could be helpful. Is it a problem that the PyPI package is of a later version than the NPM package btw? Here is an example of the added badge for the README.md file
> Add npm badge

- itkwidgets/widget_viewer.py
These will fail if `mlab` has not been imported.
> BUG: Fix mayavi imports

- README.rst
- examples/CompareImages.ipynb
- itkwidgets/__init__.py
- itkwidgets/widget_compare.py
- js/lib/viewer.js
Compare two images by visualizing them side by side.
Visualization traits, e.g. the view mode, camera, etc., are linked
between the viewers. Optional trait linking can be enabled in
widget's user interface.
Closes #86
Co-authored-by: Wei Ouyang <oeway007@gmail.com>
Co-authored-by: Matt McCormick <matt.mccormick@kitware.com>
@fjug @oeway basic version is working! :baby: :mountain:
> ENH: compare widget

- js/lib/viewer.js
- js/package-lock.json
- js/package.json
It should not be necessary due to Webpack/Babel transformations.
Avoid potential JupyterLab build errors.
> BUG: Remove babel/polyfill

- itkwidgets/_transform_types.py
With itk 5.1.0, is_arraylike will pass on an itk.Image. to_itk_image is
currently expected to return None with an itk.Image. Keep that behavior
-- this may be changed later, but dependent code will need to be
refactored.
> BUG: Do not convert itk 5.1 image since it is array-like

- setup.py
Simple fix to ensure `colorcet` is the correct version.
Resolves #308
> Require colorcet>=2.0.0

- itkwidgets/_transform_types.py
- itkwidgets/trait_types.py
- itkwidgets/widget_checkerboard.py
- itkwidgets/widget_compare.py
- itkwidgets/widget_line_profiler.py
So this function can be used to generally return an itk.Image from
something that is convertible.
> ENH: to_itk_image does not return None with itk.Image

- itkwidgets/widget_viewer.py
Addresses:
itkwidgets/widget_viewer.py:207
Traits should be given as instances, not types (for example, `Int()`,
not `Int`). Passing types is deprecated in traitlets 4.1.
itkwidgets/widget_viewer.py:326
metadata {'trait': <class 'traitlets.traitlets.CFloat'>} was set
from the constructor. With traitlets 4.1, metadata should be set
using the .tag() method, e.g., Int().tag(key1='value1',
key2='value2')
> COMP: Nested trait initialization for traitlets 4.1

- itkwidgets/_transform_types.py
Simple fix to add ``VTK_ID_TYPE`` to ``_vtk_data_type_to_vtkjs_type``.
Referenced:
https://vtk.org/doc/nightly/html/vtkType_8h_source.html
> Add VTK_ID_TYPE to mapper

- .github/workflows/build-test.yml
- itkwidgets/_transform_types.py
- requirements.txt
- setup.py
- tests/test_transform_types.py
- Update package requirements for ITK v5.2 release
- Update for PyVectorContainer template changes introduced in ITK 5.2 (this affects geometry rendering)
- Drop CI checks for Python 3.5 which is no longer maintained
Resolves package dependency issues noted in #406.
> Update for ITK 5.2

- .github/workflows/build-test.yml
- itkwidgets/_version.py
- requirements.txt
Bumps `itk` and `itk-meshtopolydata` Python dependencies to address
meshtopolydata crash in older package versions. Closes #448.
> ENH: Bump to dev 0.33.1 and update ITK package dependencies

- examples/Hello3DWorld.ipynb
- examples/NumPyArrayPointSet.ipynb
- examples/integrations/MONAI/transform_visualization.ipynb
- examples/integrations/PyImageJ/ImageJImgLib2.ipynb
- examples/integrations/PyVista/LiDAR.ipynb
- examples/integrations/PyVista/UniformGrid.ipynb
- examples/integrations/dask/DaskArray.ipynb
- examples/integrations/itk/3DImage.ipynb
- examples/integrations/vtk/vtkImageData.ipynb
- examples/integrations/vtk/vtkPolyDataPointSet.ipynb
- examples/integrations/xarray/DataArray.ipynb
- examples/integrations/zarr/OME-NGFF-Brainstem-MRI.ipynb
- itkwidgets/_type_aliases.py
- itkwidgets/integrations/__init__.py
Some notebooks made assumptions about environment or had old debug information. This PR removes debug cells and ensures we always install the correct version of `itkwidgets`. This also removes references to `itk.GroupSpatialObject`. This is not raising errors in testing in Jupyter Notebook or JupyterLab, however for some reason this errors out in Colab an prevents itkwidgets from being used.
> Notebook updates

- pyproject.toml
Addresses part of #479 by adding `imjoy-elfinder` dependency to options
> ENH: Include imjoy-elfinder in options

- examples/integrations/MONAI/transform_visualization.ipynb
- itkwidgets/viewer.py
- Fixes another bug that was introduced by the incorrectly resolved merge conflicts. Support for the `label_image` input was lost, added back in now.
- Adds the `label_image` info to the doc string
- Updates the MONAI example notebook to use `label_image`
Relies on the changes in Kitware/itk-vtk-viewer#538
> Label fixes

- itkwidgets/viewer.py
This avoids error when using multiple pointSets.
> fix(viewer): Initialize result

- docs/conf.py
Following the suggestion [here](https://protips.readthedocs.io/git-tag-version.html) this uses `git describe` to generate a version number based on current Git commit. `git describe` returns the tag name we are on (ex: `v1.0a7`).
Fixes #495
> DOCS: Infer version from git tags

- pyproject.toml
Flip
```
lab = [ "imjoy-jupyter-extension >=0.3.0", "imjoy-elfinder[jupyter]" ]
notebook = [ "imjoy-jupyterlab-extension >=0.1.13", "imjoy-elfinder[jupyter]" ]
```
to be
```
lab = [ "imjoy-jupyterlab-extension >=0.1.13", "imjoy-elfinder[jupyter]" ]
notebook = [ "imjoy-jupyter-extension >=0.3.0", "imjoy-elfinder[jupyter]" ]
```
> BUG: ImJoy extension options were flipped

- js/lib/viewer.js
Browser developer console:
```
Uncaught (in promise) TypeError: channels is null
initialize_itkVtkViewer viewer.js:933
initialize_viewer viewer.js:1852
createRenderingPipeline viewer.js:286
render viewer.js:1285
viewer.js:933:8
```
Problems:
- See #398, #429 
- `point_set_colors` does not work
- ...
1. Open e.g. `examples/NumPyArrayPointSet.ipynb`
2. Open developer console of the browser
3. Run the notebook
4. Look in the console
1. Error message in console
2. All point clouds are white (normally they have different colors)
This just adds a null check to the `channels` attribute.
Additionally, a similar case is also mitigated (`background`).
Fixes #398
Fixes #429
> BUG: Fix uninitialized variable in viewer

- .github/workflows/publish.yml
As a temporary fix to get the publish workflow working this removes the steps to generate the release notes. Right now this [fails in CI](https://github.com/InsightSoftwareConsortium/itkwidgets/actions/runs/2928577942/jobs/4672916622#step:6:9) but succeeds when run locally. Issue #521 tracks this problem to be fixed.
> BUG: Remove release notes from publish workflow

- .gitignore
Makes repo a little more approachable for folks without python stuff in their global .gitignore?
> chore: add byte compiled and venv to git ignore

- pyproject.toml
To make `pip install itkwidgets[all]` work in more situations out-of-the-box, only install the Jupyter related dependencies with Python version greater than 3.7 as a proxy for Google Colab. This works with the tools we have for dependency requirements and environments:
- https://hatch.pypa.io/latest/config/dependency/
- https://peps.python.org/pep-0508/
Google Colab has Python 3.7, not many other environments have it because it is deprecated.
The google-colab package requires tornado~=5.1.0, jupyter requires tornado>=6.2. 6.2 gets installed in Colab, and colab does not work.
This should be coupled with some ongoing work by @bnmajor to detect the running environment and throw an error if the required package dependencies are not installed for the case of Python 3.7 + Jupyter.
> COMP: Workaround Colab/Jupyter tornado dependency conflict for [all]

- itkwidgets/viewer_config.py
- Annotations are now in upper right so that they are not covered by the plane sliders
- Plane sliders are now always shown even when the panel is collapsed
> ENH: Bump viewer and UI to improve sliders

- requirements.txt
To address #588:
> TraitError: label_image_weights shape expected to have 1 components, but got () components
We also have to explicitly install notebook, ipywidgets, because they are not installed via dependencies, and set them to versions compatible to traitslets 5.6.
> COMP: Limit traitlets to <5.7.0

- docs/jupyterlite/jupyterlite_config.json
- docs/requirements.txt
With JupyterLite `0.1.0b17`, the `piplite_urls` configuration has changed and should now be put under the `PipliteAddon` field: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b17
This change also pins to `jupyterlite[all]==0.1.0b17` for now to avoid catching potential breaking changes during the beta cycle.
> Update to JupyterLite 0.1.0b17 and the `piplite_urls` config

- README.md
The link was giving a 404 otherwise.
> Update the link to the deployments page

- itkwidgets/viewer_config.py
Use `itk-vtk-viewer` `v14.27.0` which now uses `vtk.js` `v25.15.1`
> BLD: Bump itk-vtk-viewer to version 14.27.0

- .github/workflows/notebook-test.yml
Temporary fix to avoid issues with `wasmer-python` since they have no 3.11 wheels available.
> TST: Disable testing for Python 3.11

- .github/workflows/notebook-test.yml
- pyproject.toml
> BUG: Bump itkwasm dep to >= 1.0b.78 for Python 3.11 support

- itkwidgets/viewer_config.py
Adds the following changes from itk-vtk-viewer:
- Handle TAKE_SCREENSHOT event: This should hopefully prevent the occasional "No object bound to API" error we were seeing in Colab notebooks
- do not clamp the color range
> BLD: Bump itk-vtk-viewer 14.35.0 -> 14.36.0

- itkwidgets/viewer_config.py
Move swap image toggle button next to the image mix slider:
As suggested by @ebrahimebrahim
> BLD: bump itk-vtk-viewer to always show compare swap image button

- itkwidgets/viewer_config.py
Fixes the label image weighting so that only the label images are affected by changes and adds image mix animation.
> ENH: Bump itk-vtk-viewer version 14.40.3 -> 14.41.1

- pyproject.toml
As reported by @aylward: Trying to pip install --pre itkwidgets[all] produces an error when trying to compile aiohttp
The imjoy-elfinder dependency brings in aiohttp but <= 3.8.2 does not build for Python 3.11. For 3.11 make sure we use aiohttp>=3.8.2.
Stack Overflow [discussion](https://stackoverflow.com/questions/74550830/error-could-not-build-wheels-for-aiohttp-which-is-required-to-install-pyprojec) with links to relevant issues.
> BUG: Fix aiohttp dep for Python 3.11

- itkwidgets/integrations/environment.py
- pyproject.toml
With the bump to 0.1.20, the module name changed to:
imjoy_jupyterlab_extension
from:
imjoy-jupyterlab-extension
> COMP: Fix imjoy_jupyterlab_extension module detection

- itkwidgets/viewer_config.py
itk-vtk-viewer v14.46.1
Brings in https://github.com/Kitware/itk-vtk-viewer/pull/729 to address: https://github.com/InsightSoftwareConsortium/itkwidgets/issues/683
> BUG: Bump JS viewer for label image background weight 0.0

- itkwidgets/viewer.py
multiscales.images[-1] is not going to produce the expected results.
Explicitly fetch the current scale when getting the roi slice. I did not test this, but hopefully it will yield more consistent results if the viewer is exploring different resolutions.
> BUG: Fetch current scale before use in roi methods

- itkwidgets/cell_watcher.py
Fixes changes accidentally overwritten in [3c7b60b](https://github.com/InsightSoftwareConsortium/itkwidgets/pull/716/commits/3c7b60b3bc0cccb9639b5e8d3322cd357633f4b9)
> BUG: Make sure that raised exceptions abort queued cells

- itkwidgets/_initialization_params.py
- itkwidgets/viewer.py
- itkwidgets/viewer_config.py
Closes #723
Depends on:
https://github.com/Kitware/itk-vtk-viewer/pull/730#pullrequestreview-1793586609
> ENH: Add vmin and vmax to viewer

- pyproject.toml
Addressed with: https://github.com/imjoy-team/imjoy-jupyterlab-extension/pull/7
> ENH: Remove imjoy-jupyterlab-extension pin for JupyterLab>=4 support

- docs/requirements.txt
- itkwidgets/integrations/__init__.py
- pyproject.toml
Avoid conflicts with pandas version (Issue #743) and keep light.
> COMP: Only depend on dask-image in pyodide

- itkwidgets/integrations/environment.py
- pyproject.toml
- BUG: imjoy-jupyterlab-extension dep with notebook>=7
- ENH: Add check for sufficient notebook or jupyterlab version
> jupyter notebook 7

- pyproject.toml
The `notebook` dependency no longer is brought in automatically. And
specify that we need notebook>=7 with our recent updates to
imjoy-jupyterlab-extension.
> BUG: Add notebook>=7 as a dep for [notebook] installation option

- pyproject.toml
Add support for more label image downsample types, encountered with
torch / monai, via:
https://github.com/InsightSoftwareConsortium/itk-wasm/pull/1117/commits/ffb6e2cf6c8b5c3f064c16d5d51636cd85a59eae
> BUG: Bump ngff-zarr dep to 0.8.2

- .github/workflows/notebook-test.yml
> BUG: Exclude EnvironmentCheck notebook for Python 3.8

- .github/workflows/notebook-test.yml
- itkwidgets/standalone/index.html
- itkwidgets/viewer_config.py
Fleek made a major transition to new infrastructure, their fleek.co
gateway is no longer available.
Move to the Protocol Labs public dweb.link gateway.
These CID's were also pinned on Pinata.
> BUG: Move from on.fleek.co to dweb.link gateway
